// <auto-generated />
using System;
using CartaoCreditoValido.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartaoCreditoValido.Infra.Migrations
{
    [DbContext(typeof(CartaoCreditoContext))]
    [Migration("20260330141127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartaoCreditoValido.Domain.CartoesCredito.Entities.CartaoCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("NascimentoTitular")
                        .HasColumnType("date");

                    b.Property<string>("NomeCompletoTitular")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("NumeroCartao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CartoesCredito", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
